# Generated by Django 5.2.4 on 2025-07-10 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_block_users_lesson_users_and_more'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lessons',
            field=models.ManyToManyField(to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(related_name='questions', through='questions.UsersAnswers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersanswers',
            unique_together={('user', 'question')},
        ),
        migrations.DeleteModel(
            name='LessonQuestion',
        ),
    ]
