# Generated by Django 5.2.4 on 2025-07-10 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='users',
            field=models.ManyToManyField(related_name='texts', through='texts.UserText', to=settings.AUTH_USER_MODEL),
        ),
    ]
