# Generated by Django 5.2.4 on 2025-07-10 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='users',
            field=models.ManyToManyField(related_name='blocks', through='lessons.UserBlock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='users',
            field=models.ManyToManyField(related_name='lessons', through='lessons.UserLesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('user', 'block')},
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('user', 'lesson')},
        ),
    ]
